### ISSUE TITLE
linear congruential engine

### ISSUE THREAD

**Issue by engelfa** [engelfa/TuK1-CPU#11]
New random generator -> could be faster

**Comment by Chaoste** [comment]
https://www.tutorialspoint.com/cplusplus-program-to-implement-the-linear-congruential-generator-for-pseudo-random-number-generation

https://www.sanfoundry.com/cpp-program-implement-linear-congruential-generator-pseudo-random-number-generation/

**Comment by Chaoste** [comment]
This is missing in our code base so I'll reopen it

**Comment by engelfa** [comment]
No, it's in line 64 in the main.cpp:
`std::minstd_rand e2(rd());`
https://en.cppreference.com/w/cpp/numeric/random/linear_congruential_engine
