### ISSUE TITLE
option for parallel python runs

### ISSUE THREAD

**Issue by boeckhoff** [engelfa/TuK1-CPU#14]

**Comment by Chaoste** [comment]
To avoid side effects of parallelization we should look in to the CPU (core) bandwidth. However, this information appears to be hard to gather so maybe we can have a look into this when the parallel execution is implemented. We only need it to know the upper bound of concurrent runs.

**Comment by Chaoste** [comment]
If we want parallelization in C++ too, this is a good example: https://github.com/eliben/code-for-blog/blob/master/2016/threads-affinity/launch-thread-per-cpu.cpp  (compile with `-pthread`)

**Comment by boeckhoff** [comment]
use intel mlc to find out bandwidth
example values for pella: 
- on same node: 25GB
- with one hop: 10GB

**Comment by Chaoste** [comment]
Right now we already have parallelization in the python code using multiprocessing. One can define PROCESSES_PER_CORE and CONCURRENCY with python constants in utils/execution.py.
