### ISSUE TITLE
find cache size of CPU in Python and pass to C++

### ISSUE THREAD

**Issue by laurenzse** [engelfa/TuK1-CPU#2]

**Comment by boeckhoff** [comment]
run `cat /proc/cpuinfo | grep cache`

**Comment by Chaoste** [comment]
For me this only returns an overall number per core, not for each level. For the separate sizes of each level, run either ` lscpu ` or ` getconf -a | grep CACHE `

**Comment by Chaoste** [comment]
I was not sure why would need this in the C++ code instead of using it in our plots. Currently, the cache size is only printed before execution.
